apiVersion: v2
name: socialgrants
description: South Africa Social Grants Pilot System Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Vundla/My-Portfolio/social-grants-pilot
sources:
  - https://github.com/Vundla/My-Portfolio
maintainers:
  - name: DSD IT Team
    email: it-support@dsd.gov.za
keywords:
  - social-grants
  - government
  - south-africa
  - popia-compliant

annotations:
  category: Government Services
  compliance: POPIA
  security-level: high

dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 17.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: keycloak
    version: 17.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  
  - name: prometheus
    version: 19.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: 6.50.0
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled

  - name: nginx-ingress
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled